// flow-typed signature: 9e9f97200b5443fde8edb96970c098db
// flow-typed version: <<STUB>>/react-selectable-fast_v^2.1.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-selectable-fast'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-selectable-fast' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-selectable-fast/dist/react-selectable-fast' {
  declare module.exports: any;
}

declare module 'react-selectable-fast/lib/CreateSelectable' {
  declare module.exports: any;
}

declare module 'react-selectable-fast/lib/DeselectAll' {
  declare module.exports: any;
}

declare module 'react-selectable-fast/lib/doObjectsCollide' {
  declare module.exports: any;
}

declare module 'react-selectable-fast/lib/getBoundsForNode' {
  declare module.exports: any;
}

declare module 'react-selectable-fast/lib/index' {
  declare module.exports: any;
}

declare module 'react-selectable-fast/lib/nodeInRoot' {
  declare module.exports: any;
}

declare module 'react-selectable-fast/lib/SelectableGroup' {
  declare module.exports: any;
}

declare module 'react-selectable-fast/lib/SelectAll' {
  declare module.exports: any;
}

declare module 'react-selectable-fast/lib/Selectbox' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-selectable-fast/dist/react-selectable-fast.js' {
  declare module.exports: $Exports<'react-selectable-fast/dist/react-selectable-fast'>;
}
declare module 'react-selectable-fast/lib/CreateSelectable.js' {
  declare module.exports: $Exports<'react-selectable-fast/lib/CreateSelectable'>;
}
declare module 'react-selectable-fast/lib/DeselectAll.js' {
  declare module.exports: $Exports<'react-selectable-fast/lib/DeselectAll'>;
}
declare module 'react-selectable-fast/lib/doObjectsCollide.js' {
  declare module.exports: $Exports<'react-selectable-fast/lib/doObjectsCollide'>;
}
declare module 'react-selectable-fast/lib/getBoundsForNode.js' {
  declare module.exports: $Exports<'react-selectable-fast/lib/getBoundsForNode'>;
}
declare module 'react-selectable-fast/lib/index.js' {
  declare module.exports: $Exports<'react-selectable-fast/lib/index'>;
}
declare module 'react-selectable-fast/lib/nodeInRoot.js' {
  declare module.exports: $Exports<'react-selectable-fast/lib/nodeInRoot'>;
}
declare module 'react-selectable-fast/lib/SelectableGroup.js' {
  declare module.exports: $Exports<'react-selectable-fast/lib/SelectableGroup'>;
}
declare module 'react-selectable-fast/lib/SelectAll.js' {
  declare module.exports: $Exports<'react-selectable-fast/lib/SelectAll'>;
}
declare module 'react-selectable-fast/lib/Selectbox.js' {
  declare module.exports: $Exports<'react-selectable-fast/lib/Selectbox'>;
}
